version: '3.8'

services:

  mysql_db: 
    image: "mysql:8.3.0"
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      # MYSQL_DATABASE: <your database name>
    volumes:
      - db-data:/foo
      - ./scripts:/docker-entrypoint-initdb.d 
    ports:
      - "3306"
      # - "3306:3306" uncomment this and comment the above line for testing locally
    networks:
      - project_network

  # mySQL integration using Prisma and Express.js : https://www.youtube.com/watch?v=tC-P5BiWtas
  # Prisma Documentation : https://www.prisma.io/

  # user: root 
  # password:  Password123!
  # hostname: mysql_db
  # port: 3306
  # db: <your database name>

  auth:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - project_network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - project_network

networks:
  project_network:

volumes:
  db-data:
