USE video_streaming_app;
CREATE TABLE videos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW()
)